# Configuration for Release Drafter: https://github.com/release-drafter/release-drafter
name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: 💥 Breaking changes
    labels:
      - breaking
  - title: 🚀 New features and improvements
    labels:
      - enhancement
  - title: 🐛 Bug fixes
    labels:
      - bug
  - title: 📦 Dependency updates
    labels:
      - dependencies
    collapse-after: 15
  - title: 📝 Documentation updates
    labels:
      - documentation
  - title: 🌐 Community-related changes
    labels:
      - community
  - title: 👻 Maintenance
    labels:
      - chore
      - maintenance
  - title: 🚦 Tests
    labels:
      - test
  - title: ✍ Other changes
exclude-labels:
  - skip-changelog
  - invalid
template: |
  <!-- Optional: add a release summary here -->
  $CHANGES

replacers:
  - search: 'NiA'
    replace: '[Now in Android](https://github.com/gradle/nowinandroid/tree/main-declarative)'
  - search: 'NIA'
    replace: '[Now in Android](https://github.com/gradle/nowinandroid/tree/main-declarative)'

autolabeler:
  - label: 'documentation'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
 
