[versions]
# Find latest version at: https://kotlinlang.org/docs/releases.html#release-details
kotlin = "1.9.21"

# Find latest version at: https://developer.android.com/reference/tools/gradle-api
android = "8.2.0"

[libraries]
# Kotlin dependencies
kotlin-multiplatform = { module = "org.jetbrains.kotlin.multiplatform:org.jetbrains.kotlin.multiplatform.gradle.plugin", version.ref = "kotlin" }

# Android dependencies
android-agp-application = { module = "com.android.application:com.android.application.gradle.plugin", version.ref = "android" }
android-kotlin-android = { module = "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin", version.ref = "kotlin" }
